import type { DayScript, JobScript } from '../types'
import { FUSE_REPAIR, GENERATOR_REPAIR, STAGE_REPAIR } from './repairs'

const CUSTOMER = { name: 'Ayesha', side: 'right' as const }
const MAIN_ON = 'NO! Never touch a fuse box with the power on. Switch off the main first.'

export const GENERATOR_JOB: JobScript = {
  id: 'generator',
  customer: CUSTOMER,
  repair: GENERATOR_REPAIR,
  zone: { label: 'The generator', blurb: 'Dead silent, and the whole corner smells of petrol.' },
  arrival: [
    { who: 'customer', text: 'It coughed three times and died. Papa rented it all the way from Bhopal station!' },
    { who: 'player', text: 'Smell that? Petrol. Nobody light anything.' },
  ],
  rule: 'Petrol and a hot engine: fix every leak before you start anything.',
  inspect: [
    { target: 'tank', label: 'Fuel tank', prompt: 'Open the fuel cap', observation: 'Fuel tank: half full. Not the problem', ok: true },
    { target: 'fuelCrack', label: 'Fuel pipe', prompt: 'Follow the petrol smell', observation: 'Fuel pipe: cracked, dripping petrol onto the hot engine!', ok: false },
    { target: 'pullCord', label: 'Starter', prompt: 'Pull the starter', observation: 'Starter cord: snaps off in your hand', ok: false },
    { target: 'beltGuard', label: 'Belt', prompt: 'Look under the pulleys', observation: 'Belt: gone. The engine can’t turn the dynamo', ok: false },
    { target: 'oil', label: 'Oil cap', prompt: 'Check the oil', observation: 'Oil: full and clean', ok: true },
    { target: 'plug', label: 'Spark plug', prompt: 'Check the spark plug', observation: 'Spark plug: clean, and it sparks', ok: true },
    { target: 'dynamo', label: 'Dynamo', prompt: 'Spin the dynamo by hand', observation: 'Dynamo: spins freely. Fine', ok: true },
  ],
  inspectPose: { pos: [-1.2, 1.1, 1.75], target: [-1.3, 0.35, 2.9], fov: 48 },
  buildPose: { pos: [-1.0, 1.45, 1.1], target: [-1.35, 0.3, 2.85], fov: 54 },
  diagnosis: [
    { who: 'mama', text: 'Petrol dripping on a hot engine is a fire waiting to happen. Seal that pipe first, then clamp the seal.' },
    { who: 'mama', text: 'Then a new starter cord, and a belt from the engine to the dynamo. Four fixes on one little machine.' },
  ],
  goal: 'Get the generator running, safely.',
  needs: ['Fuel pipe: a tube that sleeves it, petrol-proof', 'Clamp: thin, strong, twistable', 'Starter cord: long and strong, no stretch', 'Belt: grippy and strong'],
  focus: ['strength', 'grip', 'seal'],
  walkthrough: [
    { item: 'penRefill', joint: 'fuel', pick: 'Pick up the empty pen refill. Its tube slides right over the cracked pipe.', attach: ['Sleeve the crack in the fuel pipe.'] },
    { item: 'steelWire', joint: 'clamp', pick: 'Pick up the steel wire. Twisted round, it clamps the sleeve tight.', attach: ['Twist it round the sleeve.'] },
    { item: 'nylonRope', joint: 'cord', pick: 'Pick up the nylon rope. Charpai rope takes a hard yank.', attach: ['Tie it to the starter handle.'] },
    {
      item: 'innerTube',
      joint: 'belt',
      pick: 'Pick up the inner tube. A ring of tube grips pulleys like nothing else.',
      attach: ['Loop it round the engine pulley.', 'Now round the dynamo pulley.'],
    },
  ],
  solution: 'Pen refill over the cracked pipe, steel wire twisted round it, nylon rope on the starter, and a ring of inner tube as the belt.',
  reward: { money: 400, reputation: 12 },
  ratingLines: {
    1: { who: 'customer', text: 'It runs! …Why is it making that noise?' },
    2: { who: 'customer', text: 'It’s humming! Papa will think you’re a magician.' },
    3: { who: 'customer', text: 'Listen to it purr! Better than when it came from Bhopal!' },
  },
  thanks: [{ who: 'player', text: 'Generator done. Next!' }],
  test: { stageAt: [600, 1400, 2200, 3100], duration: 4200, hum: 50, pops: { 'no-start': 0.45 } },
}

export const FUSE_JOB: JobScript = {
  id: 'fuseBox',
  customer: CUSTOMER,
  repair: FUSE_REPAIR,
  zone: { label: 'The fuse box', blurb: 'Up on the pole. It smoked, and now the whole line is dead.' },
  arrival: [
    { who: 'customer', text: 'The electrician went home to get ready for the wedding. Of course he did.' },
    { who: 'player', text: 'Nobody touches this box until the main is off.' },
  ],
  rule: 'Mains power can kill. Switch off the main before you touch anything, and never cheat a fuse.',
  inspect: [
    { target: 'mainSwitch', label: 'Main switch', prompt: 'Pull the main switch down', observation: 'Main switch: OFF. Now it’s safe to open', ok: true },
    {
      target: 'fuseCarrier',
      label: 'Fuse',
      prompt: 'Pull out the fuse carrier',
      observation: 'Fuse: the thin wire inside has melted',
      ok: false,
      requires: 'mainSwitch',
      blocked: MAIN_ON,
    },
    {
      target: 'terminal',
      label: 'Terminal',
      prompt: 'Check the terminal screws',
      observation: 'Terminal: one screw is loose and black from sparking',
      ok: false,
      requires: 'mainSwitch',
      blocked: MAIN_ON,
    },
    { target: 'cover', label: 'Cover', prompt: 'Look at the cover', observation: 'Cover: cracked. Live copper shows through', ok: false },
    { target: 'meter', label: 'Meter', prompt: 'Read the meter', observation: 'Meter: fine', ok: true },
    {
      target: 'load',
      label: 'Extension board',
      prompt: 'Count what’s plugged in',
      observation: 'Load: the halwai’s heater, three coolers and the DJ on one board. That’s what blew it. Ayesha unplugs the heater',
      ok: true,
    },
  ],
  inspectPose: { pos: [0.1, 1.3, 2.25], target: [0.1, 1.0, 3.25], fov: 46 },
  buildPose: { pos: [-0.05, 1.7, 1.65], target: [0.0, 0.9, 3.25], fov: 54 },
  diagnosis: [
    { who: 'mama', text: 'The fuse did its job. Too much load, so it melted and saved the wiring.' },
    { who: 'mama', text: 'Replace it with something just as weak. People put coins in fuses. Then the wires burn, and so do houses.' },
    { who: 'mama', text: 'Tighten that terminal, and cover the crack.' },
  ],
  goal: 'Get the power back on, safely.',
  needs: ['Fuse: a hair-thin conductor that melts easily', 'Screwdriver: a thin, flat, stiff edge', 'Cover: sticky, and doesn’t conduct'],
  focus: ['conductivity', 'strength', 'rigidity'],
  walkthrough: [
    { item: 'fuseStrand', joint: 'fuse', pick: 'Pick up the single copper strand. Thin enough to melt before the cables do.', attach: ['Wind it across the fuse carrier.'] },
    { item: 'spoon', joint: 'screw', pick: 'Pick up the spoon. Its handle is a fine screwdriver.', attach: ['Tighten the loose terminal screw.'] },
    { item: 'tape', joint: 'cover', pick: 'Pick up the cloth tape. It sticks, and it doesn’t conduct.', attach: ['Tape over the crack in the cover.'] },
  ],
  solution: 'The single copper strand as the fuse wire (never a coin!), the spoon handle on the terminal screw, and tape over the crack.',
  reward: { money: 300, reputation: 12 },
  ratingLines: {
    1: { who: 'customer', text: 'The meter’s spinning! Is it safe?' },
    2: { who: 'customer', text: 'Power’s back on the line! And it’s safe?' },
    3: { who: 'customer', text: 'Safe AND on! The electrician couldn’t have done better.' },
  },
  thanks: [{ who: 'player', text: 'Fuse box done. Next!' }],
  test: { stageAt: [700, 1700, 2600], duration: 3800, pops: { burn: 0.5 } },
}

export const STAGE_JOB: JobScript = {
  id: 'stage',
  customer: CUSTOMER,
  repair: STAGE_REPAIR,
  zone: { label: 'The stage', blurb: 'Bunty’s mic is dead, and the light arch keeps going BANG.' },
  arrival: [
    { who: 'visitor', name: 'Bunty', text: 'A goat, yaar. It ate my mic cable like Maggi.' },
    { who: 'customer', text: 'And the arch sparks every time the power comes back.' },
  ],
  rule: 'Every joint gets covered. Bare wires touch, and touching wires go bang.',
  inspect: [
    { target: 'amp', label: 'Amp', prompt: 'Switch on the amp', observation: 'Amp: lights up on the shop battery. Fine', ok: true },
    { target: 'micCut', label: 'Mic cable', prompt: 'Follow the mic cable', observation: 'Mic cable: chewed clean through', ok: false },
    { target: 'archShort', label: 'Arch wiring', prompt: 'Look up at the arch', observation: 'Arch: two bare wires touching. Short circuit!', ok: false },
    { target: 'bulbs', label: 'Bulbs', prompt: 'Check the bulbs', observation: 'Bulbs: all fine', ok: true },
    { target: 'speakerStand', label: 'Speaker', prompt: 'Shake the speaker', observation: 'Speaker: your Day 5 fix. Still rock solid', ok: true },
  ],
  inspectPose: { pos: [0.45, 1.65, 2.05], target: [1.55, 0.75, 4.0], fov: 54 },
  buildPose: { pos: [1.0, 2.2, 1.25], target: [1.35, 0.45, 3.45], fov: 58 },
  diagnosis: [
    { who: 'mama', text: 'Join the mic cable, then cover that joint. Bunty grabs cables with wet hands.' },
    { who: 'mama', text: 'And keep those arch wires apart with something that doesn’t conduct.' },
  ],
  goal: 'Get the mic and the light arch working.',
  needs: ['Join: carries current', 'Joint cover: sticky, no metal', 'Spacer: keeps wires apart, no metal'],
  focus: ['conductivity', 'seal', 'flexibility'],
  walkthrough: [
    { item: 'wire', joint: 'splice', pick: 'Pick up the copper wire.', attach: ['Join the two chewed ends.'] },
    { item: 'tape', joint: 'wrap', pick: 'Pick up the tape.', attach: ['Wrap the joint tight.'] },
    { item: 'innerTube', joint: 'separate', pick: 'Pick up the inner tube. Rubber keeps wires apart.', attach: ['Slip it between the touching wires.'] },
  ],
  solution: 'Copper wire joins the mic cable, tape wraps the joint, and a strip of inner tube keeps the arch wires apart.',
  reward: { money: 250, reputation: 10 },
  ratingLines: {
    1: { who: 'visitor', name: 'Bunty', text: 'Check, check… it crackles, but it’s alive!' },
    2: { who: 'visitor', name: 'Bunty', text: 'Check, check, one-two! Bunty Band is BACK!' },
    3: { who: 'visitor', name: 'Bunty', text: 'Crystal clear! That goat did me a favour!' },
  },
  thanks: [{ who: 'player', text: 'Stage done!' }],
  test: { stageAt: [600, 1500, 2400], duration: 3600, pops: { short: 0.7 } },
}

export const DAY_SEVEN: DayScript = {
  day: 7,
  recommend: 'self',
  askMama: true,
  night: true,
  zones: {
    prompt: 'Three things are dead, and the pheras won’t wait. Where first?',
    pose: { pos: [0.15, 2.6, -0.35], target: [0.1, 0.8, 3.4], fov: 60 },
  },
  countdown: {
    ms: 12 * 60_000,
    label: 'PHERAS IN',
    penaltyMs: 30_000,
    lateLabel: 'THE PANDIT IS WAITING',
    lateNote: 'One star off: the pheras started late.',
  },
  companions: [
    { visitor: 'bunty', at: [2.9, 0, 3.05] },
    { visitor: 'masterJi', at: [-1.45, 0, 4.25] },
    { visitor: 'sharma', at: [-1.85, 0, 4.25] },
    { visitor: 'rafiq', at: [-0.35, 0, 4.25] },
    { visitor: 'khanna', at: [-2.55, 0, 4.2] },
    { visitor: 'rocky', at: [-2.85, 0, 3.1] },
  ],
  morningCues: { 2: 'pop' },
  morning: [
    { who: 'customer', text: 'You came! Look at the lane, it’s glowing. Didi looks like a queen tonight.' },
    { who: 'visitor', name: 'Bunty', text: 'Bunty Band, ready! Dhol, trumpet, and the new mic. One, two, thr—' },
    { who: 'player', text: '…Why did everything go dark?' },
    { who: 'visitor', name: 'Mr. Khanna', text: 'The generator coughed and died. And the fuse box on the pole is smoking!' },
    { who: 'visitor', name: 'Bunty', text: 'And my mic is dead. A goat was chewing the cable. A GOAT.' },
    { who: 'customer', text: 'The pandit says the pheras must start at the auspicious time. Twelve minutes from now!' },
    { who: 'visitor', name: 'Rocky', text: 'Don’t look at me. There’s no app for this. …I’ll hold the torch.' },
    { who: 'player', text: 'Twelve minutes. Ho jayega.' },
  ],
  jobs: [GENERATOR_JOB, FUSE_JOB, STAGE_JOB],
  evening: {
    visitor: 'mama',
    name: 'Mama',
    lines: [
      { who: 'visitor', name: 'Bunty', text: 'Pheras done! And Bunty Band played all night!' },
      { who: 'visitor', name: 'Master Ji', text: 'Twelve blouses, and not one stitch came loose.' },
      { who: 'visitor', name: 'Sharma Uncle', text: 'And my old fan is cooling the halwai. Rubber band and all.' },
      { who: 'visitor', name: 'Rafiq Bhai', text: 'Chai for everyone! On the house. Just this once.' },
      { who: 'visitor', name: 'Mr. Khanna', text: 'The groom’s car made it. So did the groom, somehow.' },
      { who: 'visitor', name: 'Rocky', text: '…Fine. You’re good. Teach me the rubber band thing sometime.' },
      { who: 'visitor', name: 'Ayesha', text: 'Didi says thank you. You saved her wedding.' },
      { who: 'visitor', text: 'I leave for one week…' },
      { who: 'visitor', text: 'A fuse from one copper strand. A belt from an inner tube. Who taught you all this?' },
      { who: 'player', text: 'Your diary, Mama.' },
      { who: 'visitor', text: 'Hmm. Then the diary is yours now. And the shop.' },
      { who: 'visitor', text: 'Tomorrow, repaint the sign. It doesn’t say HO JAYEGA any more.' },
      { who: 'player', text: 'HO GAYA.' },
    ],
  },
  reportTitle: (failedTests) => (failedTests === 0 ? 'Shaadi Saviour' : 'The Show Went On'),
  endLine: 'The lights stayed on all night.',
  finale: {
    title: 'Mama’s shop is yours',
    sign: { before: 'HO JAYEGA', after: 'HO GAYA' },
    lines: [
      'Seven days ago, Mama left you the keys and a diary.',
      'A rubber band. A bottle cap. An inner tube. One copper strand.',
      'Every fix a little jugaad, and every one of them held.',
      'The lane has its repair shop back.',
    ],
    footer: 'Thank you for playing HO JAYEGA. Made in 48 hours for MP Game Udaan.',
  },
}
